// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for InvokeUsingHEAD.
    /// </summary>
    public static partial class InvokeUsingHEADExtensions
    {
            /// <summary>
            /// invoke
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void One(this IInvokeUsingHEAD operations)
            {
                operations.OneAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// invoke
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task OneAsync(this IInvokeUsingHEAD operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.OneWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
