// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AdminStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the AdminStatusResponse class.
        /// </summary>
        public AdminStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AdminStatusResponse class.
        /// </summary>
        public AdminStatusResponse(string status = default(string))
        {
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
