// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AlgoTest
    {
        /// <summary>
        /// Initializes a new instance of the AlgoTest class.
        /// </summary>
        public AlgoTest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AlgoTest class.
        /// </summary>
        public AlgoTest(Algo algo = default(Algo), string containerId = default(string), long? id = default(long?), string status = default(string))
        {
            Algo = algo;
            ContainerId = containerId;
            Id = id;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "algo")]
        public Algo Algo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "containerId")]
        public string ContainerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
