// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AlgoUser
    {
        /// <summary>
        /// Initializes a new instance of the AlgoUser class.
        /// </summary>
        public AlgoUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AlgoUser class.
        /// </summary>
        public AlgoUser(object algos = default(object), long? id = default(long?), string userName = default(string))
        {
            Algos = algos;
            Id = id;
            UserName = userName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "algos")]
        public object Algos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

    }
}
