// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LogResponse
    {
        /// <summary>
        /// Initializes a new instance of the LogResponse class.
        /// </summary>
        public LogResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LogResponse class.
        /// </summary>
        public LogResponse(string log = default(string))
        {
            Log = log;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "log")]
        public string Log { get; set; }

    }
}
