// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ResourceSupport
    {
        /// <summary>
        /// Initializes a new instance of the ResourceSupport class.
        /// </summary>
        public ResourceSupport()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceSupport class.
        /// </summary>
        public ResourceSupport(IList<Link> links = default(IList<Link>))
        {
            Links = links;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public IList<Link> Links { get; set; }

    }
}
