// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.DeploymentApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class View
    {
        /// <summary>
        /// Initializes a new instance of the View class.
        /// </summary>
        public View()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the View class.
        /// </summary>
        public View(string contentType = default(string))
        {
            ContentType = contentType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; set; }

    }
}
