// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.KubernetesClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// NamespaceStatus is information about the current status of a Namespace.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1NamespaceStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NamespaceStatus class.
        /// </summary>
        public Iok8skubernetespkgapiv1NamespaceStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NamespaceStatus class.
        /// </summary>
        /// <param name="phase">Phase is the current lifecycle phase of the
        /// namespace. More info:
        /// https://git.k8s.io/community/contributors/design-proposals/namespaces.md#phases</param>
        public Iok8skubernetespkgapiv1NamespaceStatus(string phase = default(string))
        {
            Phase = phase;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets phase is the current lifecycle phase of the namespace.
        /// More info:
        /// https://git.k8s.io/community/contributors/design-proposals/namespaces.md#phases
        /// </summary>
        [JsonProperty(PropertyName = "phase")]
        public string Phase { get; set; }

    }
}
