// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.KubernetesClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// PersistentVolumeClaimStatus is the current status of a persistent
    /// volume claim.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1PersistentVolumeClaimStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PersistentVolumeClaimStatus class.
        /// </summary>
        public Iok8skubernetespkgapiv1PersistentVolumeClaimStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PersistentVolumeClaimStatus class.
        /// </summary>
        /// <param name="accessModes">AccessModes contains the actual access
        /// modes the volume backing the PVC has. More info:
        /// https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1</param>
        /// <param name="capacity">Represents the actual resources of the
        /// underlying volume.</param>
        /// <param name="phase">Phase represents the current phase of
        /// PersistentVolumeClaim.</param>
        public Iok8skubernetespkgapiv1PersistentVolumeClaimStatus(IList<string> accessModes = default(IList<string>), IDictionary<string, string> capacity = default(IDictionary<string, string>), string phase = default(string))
        {
            AccessModes = accessModes;
            Capacity = capacity;
            Phase = phase;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets accessModes contains the actual access modes the
        /// volume backing the PVC has. More info:
        /// https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
        /// </summary>
        [JsonProperty(PropertyName = "accessModes")]
        public IList<string> AccessModes { get; set; }

        /// <summary>
        /// Gets or sets represents the actual resources of the underlying
        /// volume.
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public IDictionary<string, string> Capacity { get; set; }

        /// <summary>
        /// Gets or sets phase represents the current phase of
        /// PersistentVolumeClaim.
        /// </summary>
        [JsonProperty(PropertyName = "phase")]
        public string Phase { get; set; }

    }
}
