// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.KubernetesClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// NodeSpec describes the attributes that a node is created with.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1NodeSpec
    {
        /// <summary>
        /// Initializes a new instance of the Iok8skubernetespkgapiv1NodeSpec
        /// class.
        /// </summary>
        public Iok8skubernetespkgapiv1NodeSpec()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8skubernetespkgapiv1NodeSpec
        /// class.
        /// </summary>
        /// <param name="externalID">External ID of the node assigned by some
        /// machine database (e.g. a cloud provider). Deprecated.</param>
        /// <param name="podCIDR">PodCIDR represents the pod IP range assigned
        /// to the node.</param>
        /// <param name="providerID">ID of the node assigned by the cloud
        /// provider in the format:
        /// &lt;ProviderName&gt;://&lt;ProviderSpecificNodeID&gt;</param>
        /// <param name="taints">If specified, the node's taints.</param>
        /// <param name="unschedulable">Unschedulable controls node
        /// schedulability of new pods. By default, node is schedulable. More
        /// info:
        /// https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration</param>
        public Iok8skubernetespkgapiv1NodeSpec(string externalID = default(string), string podCIDR = default(string), string providerID = default(string), IList<Iok8skubernetespkgapiv1Taint> taints = default(IList<Iok8skubernetespkgapiv1Taint>), bool? unschedulable = default(bool?))
        {
            ExternalID = externalID;
            PodCIDR = podCIDR;
            ProviderID = providerID;
            Taints = taints;
            Unschedulable = unschedulable;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets external ID of the node assigned by some machine
        /// database (e.g. a cloud provider). Deprecated.
        /// </summary>
        [JsonProperty(PropertyName = "externalID")]
        public string ExternalID { get; set; }

        /// <summary>
        /// Gets or sets podCIDR represents the pod IP range assigned to the
        /// node.
        /// </summary>
        [JsonProperty(PropertyName = "podCIDR")]
        public string PodCIDR { get; set; }

        /// <summary>
        /// Gets or sets ID of the node assigned by the cloud provider in the
        /// format:
        /// &amp;lt;ProviderName&amp;gt;://&amp;lt;ProviderSpecificNodeID&amp;gt;
        /// </summary>
        [JsonProperty(PropertyName = "providerID")]
        public string ProviderID { get; set; }

        /// <summary>
        /// Gets or sets if specified, the node's taints.
        /// </summary>
        [JsonProperty(PropertyName = "taints")]
        public IList<Iok8skubernetespkgapiv1Taint> Taints { get; set; }

        /// <summary>
        /// Gets or sets unschedulable controls node schedulability of new
        /// pods. By default, node is schedulable. More info:
        /// https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration
        /// </summary>
        [JsonProperty(PropertyName = "unschedulable")]
        public bool? Unschedulable { get; set; }

    }
}
