// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.KubernetesClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents downward API info for projecting into a projected volume.
    /// Note that this is identical to a downwardAPI volume source without the
    /// default mode.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1DownwardAPIProjection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1DownwardAPIProjection class.
        /// </summary>
        public Iok8skubernetespkgapiv1DownwardAPIProjection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1DownwardAPIProjection class.
        /// </summary>
        /// <param name="items">Items is a list of DownwardAPIVolume
        /// file</param>
        public Iok8skubernetespkgapiv1DownwardAPIProjection(IList<Iok8skubernetespkgapiv1DownwardAPIVolumeFile> items = default(IList<Iok8skubernetespkgapiv1DownwardAPIVolumeFile>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets items is a list of DownwardAPIVolume file
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Iok8skubernetespkgapiv1DownwardAPIVolumeFile> Items { get; set; }

    }
}
